### ISSUE TITLE
Is this package is still maintenance?

### ISSUE THREAD

**Issue by thearabbit** [Sewdn/meteor-collection-behaviours#31]
Is this package still maintenance?
Could I use IT?

**Comment by aramk** [comment]
I've been using a fork with some custom tweaks. There may be compatibility issues with the latest version of Meteor and collection-hooks. See https://github.com/matb33/meteor-collection-hooks/pull/240. I'm using the branch https://github.com/aramk/meteor-collection-behaviours/tree/feature/soft-delete-improvements

**Comment by thearabbit** [comment]
Hi @aramk, I could not found your fork package in `atmospherejs.com`.
Please

**Comment by thearabbit** [comment]
I tried to fork your package, but get error
```
TypeError: Cannot read property 'insert' of undefined
W20180719-09:51:31.009(7)? (STDERR)     at ns.Collection.<anonymous> (packages/theara:collection-behaviours/behaviours/timestampable.js:6:15)
W20180719-09:51:31.009(7)? (STDERR)     at ns.Collection.self.(anonymous function) [as timestampable] (packages/theara:collection-behaviours/collectio
```

**Comment by aramk** [comment]
Are you on the right branch? `feature/soft-delete-improvements`

**Comment by thearabbit** [comment]
Oh thanks, I base on `master` 👍
